
import Header from "@widgets/Header/ui";
import type { Metadata } from "next";
import '@shared/styles/global.scss';

export const metadata: Metadata = {
  title: "Nevo Devs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Header/>
        {children}
      </body>
    </html>
  );
}
